import { prisma } from '@/lib/prisma';

export async function getCompanyBranding(companyId: string) {
  const company = await prisma.company.findUnique({
    where: { id: companyId },
    include: { settings: true },
  });

  const settings = new Map(company?.settings.map((s) => [s.key, s.value]) ?? []);

  return {
    name: company?.name ?? 'Company',
    nameBn: company?.nameBn ?? '',
    logoUrl: company?.logoUrl ?? '',
    address: company?.address ?? '',
    phone: company?.phone ?? '',
    email: company?.email ?? '',
    website: company?.website ?? '',
    receiptPrefix: settings.get('receiptPrefix') ?? 'RCP',
    reportFooterNote: settings.get('reportFooterNote') ?? 'Generated by Sharebuild ERP',
    defaultCurrency: settings.get('defaultCurrency') ?? 'BDT',
  };
}
