export function ReportFooter({ note }: { note?: string }) {
  return (
    <div className="mt-6 border-t pt-3 text-center text-xs text-muted-foreground print:mt-4">
      <p>{note || 'Generated by Sharebuild ERP'}</p>
      <p>Generated by Sharebuild ERP</p>
    </div>
  );
}
