import { formatDate } from '@/lib/utils';

interface ReportBranding {
  name: string;
  nameBn?: string;
  logoUrl?: string;
  address?: string;
  phone?: string;
  email?: string;
  website?: string;
  reportFooterNote?: string;
}

interface ReportHeaderProps {
  branding: ReportBranding;
  project?: {
    name: string;
    nameBn?: string | null;
    code?: string | null;
    address?: string | null;
    phone?: string | null;
  };
  title: string;
  subtitle?: string;
}

export function ReportHeader({ branding, project, title, subtitle }: ReportHeaderProps) {
  return (
    <div className="rounded-md border bg-background p-5 print:border-0 print:p-0">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div className="h-12 w-12 rounded-md border bg-muted flex items-center justify-center overflow-hidden text-xs font-semibold text-muted-foreground">
            {branding.logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={branding.logoUrl} alt={`${branding.name} logo`} className="h-full w-full object-contain" />
            ) : (
              'Logo'
            )}
          </div>
          <div>
            <h1 className="text-lg font-bold leading-tight">{branding.name}</h1>
            {branding.nameBn && <p className="bn text-sm text-muted-foreground">{branding.nameBn}</p>}
            <p className="text-xs text-muted-foreground">
              {[branding.address, branding.phone, branding.email, branding.website].filter(Boolean).join(' | ')}
            </p>
          </div>
        </div>
        <div className="text-right text-xs text-muted-foreground">
          <p>Generated {formatDate(new Date())}</p>
          <p>{branding.reportFooterNote ?? 'Generated by Sharebuild ERP'}</p>
        </div>
      </div>

      <div className="mt-5 border-t pt-4">
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Report</p>
        <h2 className="text-2xl font-bold">{title}</h2>
        {subtitle && <p className="text-sm text-muted-foreground">{subtitle}</p>}
        {project && (
          <div className="mt-3 rounded-md bg-muted/40 px-3 py-2 text-sm">
            <div className="font-semibold">{project.name}{project.code ? ` (${project.code})` : ''}</div>
            {project.nameBn && <div className="bn text-xs text-muted-foreground">{project.nameBn}</div>}
            <div className="text-xs text-muted-foreground">
              {[project.address, project.phone].filter(Boolean).join(' | ')}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
