'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { FormError, FormSuccess, FormSection, TextareaField, TextField } from '@/components/shared/form-field';
import { Loader2 } from 'lucide-react';

type CompanySettingsData = {
  name: string;
  nameBn?: string | null;
  logoUrl?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  registrationNo?: string | null;
  taxId?: string | null;
  defaultCurrency?: string;
  receiptPrefix?: string;
  defaultServiceChargePct?: string;
  fiscalYearStart?: string;
  reportFooterNote?: string;
  notes?: string;
};

export function CompanySettingsForm({ initial }: { initial: CompanySettingsData }) {
  const router = useRouter();
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const [name, setName] = useState(initial.name ?? '');
  const [nameBn, setNameBn] = useState(initial.nameBn ?? '');
  const [logoUrl, setLogoUrl] = useState(initial.logoUrl ?? '');
  const [address, setAddress] = useState(initial.address ?? '');
  const [phone, setPhone] = useState(initial.phone ?? '');
  const [email, setEmail] = useState(initial.email ?? '');
  const [website, setWebsite] = useState(initial.website ?? '');
  const [registrationNo, setRegistrationNo] = useState(initial.registrationNo ?? '');
  const [taxId, setTaxId] = useState(initial.taxId ?? '');
  const [defaultCurrency, setDefaultCurrency] = useState(initial.defaultCurrency ?? 'BDT');
  const [receiptPrefix, setReceiptPrefix] = useState(initial.receiptPrefix ?? 'RCP');
  const [defaultServiceChargePct, setDefaultServiceChargePct] = useState(initial.defaultServiceChargePct ?? '');
  const [fiscalYearStart, setFiscalYearStart] = useState(initial.fiscalYearStart ?? '');
  const [reportFooterNote, setReportFooterNote] = useState(initial.reportFooterNote ?? 'Generated by Sharebuild ERP');
  const [notes, setNotes] = useState(initial.notes ?? '');
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [removeLogo, setRemoveLogo] = useState(false);

  const logoPreview = logoFile ? URL.createObjectURL(logoFile) : removeLogo ? '' : logoUrl;

  function getErrorMessage(data: any) {
    if (typeof data?.error === 'string') return data.error;
    const formError = data?.error?.formErrors?.[0];
    if (formError) return formError;
    const fieldErrors = data?.error?.fieldErrors;
    if (fieldErrors) {
      const firstField = Object.keys(fieldErrors)[0];
      const firstMessage = firstField ? fieldErrors[firstField]?.[0] : '';
      if (firstMessage) return firstMessage;
    }
    return 'Failed to save company settings.';
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    setSuccess('');
    if (!name.trim()) {
      setError('Company name is required.');
      return;
    }

    setSaving(true);
    try {
      const data = new FormData();
      data.set('name', name.trim());
      if (nameBn.trim()) data.set('nameBn', nameBn.trim());
      if (logoUrl.trim()) data.set('logoUrl', logoUrl.trim());
      if (address.trim()) data.set('address', address.trim());
      if (phone.trim()) data.set('phone', phone.trim());
      if (email.trim()) data.set('email', email.trim());
      if (website.trim()) data.set('website', website.trim());
      if (registrationNo.trim()) data.set('registrationNo', registrationNo.trim());
      if (taxId.trim()) data.set('taxId', taxId.trim());
      data.set('defaultCurrency', defaultCurrency.trim() || 'BDT');
      if (receiptPrefix.trim()) data.set('receiptPrefix', receiptPrefix.trim());
      if (defaultServiceChargePct) data.set('defaultServiceChargePct', defaultServiceChargePct);
      if (fiscalYearStart.trim()) data.set('fiscalYearStart', fiscalYearStart.trim());
      if (reportFooterNote.trim()) data.set('reportFooterNote', reportFooterNote.trim());
      if (notes.trim()) data.set('notes', notes.trim());
      if (logoFile) data.set('logoFile', logoFile);
      if (removeLogo) data.set('removeLogo', 'true');

      const res = await fetch('/api/company/settings', { method: 'PUT', body: data });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        setError(getErrorMessage(data));
        return;
      }

      setSuccess('Company settings saved.');
      setLogoFile(null);
      setRemoveLogo(false);
      router.refresh();
    } catch {
      setError('Network error. Check your connection and try again.');
    } finally {
      setSaving(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <FormError message={error} />
      <FormSuccess message={success} />

      <FormSection title="Company Profile">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <TextField label="Company Name" id="companyName" required value={name} onChange={e => setName(e.target.value)} />
          <TextField label="Bangla Name" id="companyNameBn" value={nameBn} onChange={e => setNameBn(e.target.value)} className="bn" />
          <TextField label="Phone" id="companyPhone" value={phone} onChange={e => setPhone(e.target.value)} />
          <TextField label="Email" id="companyEmail" type="email" value={email} onChange={e => setEmail(e.target.value)} />
          <TextField label="Website" id="companyWebsite" value={website} onChange={e => setWebsite(e.target.value)} />
          <TextField label="Registration / Trade License" id="registrationNo" value={registrationNo} onChange={e => setRegistrationNo(e.target.value)} />
          <TextField label="TIN / VAT" id="taxId" value={taxId} onChange={e => setTaxId(e.target.value)} />
          <TextField label="Logo URL / Path" id="logoUrl" value={logoUrl} onChange={e => setLogoUrl(e.target.value)} />
        </div>
        <TextareaField label="Address" id="companyAddress" value={address} onChange={e => setAddress(e.target.value)} rows={2} />
        <div className="grid grid-cols-1 md:grid-cols-[160px_1fr] gap-4 rounded-md border p-4">
          <div className="flex h-24 w-36 items-center justify-center overflow-hidden rounded-md border bg-muted/30">
            {logoPreview ? (
              <img src={logoPreview} alt={`${name || 'Company'} logo`} className="max-h-full max-w-full object-contain" />
            ) : (
              <span className="text-xs text-muted-foreground">No logo</span>
            )}
          </div>
          <div className="space-y-3">
            <div>
              <label htmlFor="logoFile" className="text-sm font-medium">Upload Logo</label>
              <input
                id="logoFile"
                type="file"
                accept="image/png,image/jpeg,image/webp"
                onChange={(e) => {
                  setLogoFile(e.target.files?.[0] ?? null);
                  setRemoveLogo(false);
                }}
                className="mt-1 block text-sm"
              />
              <p className="mt-1 text-xs text-muted-foreground">JPG, PNG, or WebP up to 2 MB. Used on report and print headers.</p>
            </div>
            {(logoPreview || logoUrl) && (
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setLogoFile(null);
                  setLogoUrl('');
                  setRemoveLogo(true);
                }}
              >
                Remove Logo
              </Button>
            )}
          </div>
        </div>
      </FormSection>

      <FormSection title="Defaults">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <TextField label="Default Currency" id="defaultCurrency" value={defaultCurrency} onChange={e => setDefaultCurrency(e.target.value)} />
          <TextField label="Receipt Prefix" id="receiptPrefix" value={receiptPrefix} onChange={e => setReceiptPrefix(e.target.value)} />
          <TextField label="Default Service Charge %" id="defaultServiceChargePct" type="number" min={0} step="0.01" value={defaultServiceChargePct} onChange={e => setDefaultServiceChargePct(e.target.value)} />
          <TextField label="Fiscal Year Start" id="fiscalYearStart" placeholder="e.g. July 1" value={fiscalYearStart} onChange={e => setFiscalYearStart(e.target.value)} />
        </div>
        <TextField label="Report Footer Note" id="reportFooterNote" value={reportFooterNote} onChange={e => setReportFooterNote(e.target.value)} />
        <TextareaField label="Notes" id="companyNotes" value={notes} onChange={e => setNotes(e.target.value)} rows={3} />
      </FormSection>

      <Button type="submit" disabled={saving}>
        {saving ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Saving...</> : 'Save Company Settings'}
      </Button>
    </form>
  );
}
